chore(github-action): Avoid builds for pushes to changelog directory
openebs/libcstor pull request #85
Opened 2021-04-07 12:25 UTC by niladrih

Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>

The build.yml and pull_request.yml workflows will ignore pushes made to `changelogs/` directory. This will result in images not built for pushes made to it.

2021-04-07 14:20 UTC, niladrih commented
Related PRs:
https://github.com/openebs/node-disk-manager/pull/562
https://github.com/openebs/cstor-operators/pull/271
https://github.com/openebs/dynamic-localpv-provisioner/pull/41
https://github.com/openebs/zfs-localpv/pull/306
https://github.com/openebs/lvm-localpv/pull/42
https://github.com/openebs/jiva-operator/pull/66
https://github.com/openebs/maya/pull/1797
https://github.com/openebs/cstor-csi/pull/151
https://github.com/openebs/jiva/pull/350
https://github.com/openebs/velero-plugin/pull/151
https://github.com/openebs/m-exporter/pull/14

2021-04-28 14:07 UTC, akhilerm commented on .github/workflows/release.yml
Tags need to be mentioned here.

2021-04-28 14:08 UTC, akhilerm requested changes
Some comments in the release workflow. Also can you make the same changes in all the related PRs. @niladrih

2021-04-28 14:20 UTC, akhilerm approved these changes
LGTM

2021-04-29 18:25 UTC, niladrih commented
@akhilerm @shubham14bajpai -- Should a workflow job be added to `pull_request.yml` to build the cstor-pool image? Presently only cstor-base is being built.

2021-04-30 05:24 UTC, niladrih commented
Leaving cstor-pool build out of pull_request.yml because cstor-base and cstor-pool just have a different entrypoint, and cstor-base build is sufficient.
cc: @shubham14bajpai

2021-05-05 07:29 UTC, akhilerm commented
@shubham14bajpai PTAL.

2021-05-05 14:26 UTC, shubham14bajpai approved these changes
LGTM

2021-05-05 15:04 UTC, merged